AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Creates API Gateway and sets up a dynamodb
Parameters:
  Stage:
    Default: dev
    Type: String

Resources:
  DragonsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: dragons
      PrimaryKey:
        Name: id
        Type: String

  APIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: APIPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
             - "dynamodb:PutItem"
             - "dynamodb:UpdateItem"
             - "dynamodb:DeleteItem"
             - "dynamodb:GetItem"
             - "dynamodb:Scan"
            Resource:
            - Fn::Sub: ${DragonsTable.Arn}
            - Fn::Sub: ${DragonsTable.Arn}/*

  Api:
   Type: AWS::Serverless::Api
   Properties:
     StageName: !Ref Stage
     OpenApiVersion: 3.0.2
     DefinitionBody:
       Fn::Transform:
         Name: AWS::Include
         Parameters:
           Location: openapi.yaml

Outputs:
  Url:
   Description: Endpoint URL
   Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
